Feature/be/2/kakao login 카카오 로그인을 이용한 회원가입 및 로그인
HARl803/auth-service pull request #3
Opened 2024-07-31 02:41 UTC by fsm12

## 🗂️ 이슈 연결
- closes: #2  

</br>

## 📌 구현한 API
- 카카오 로그인 화면 진입 : `Get /api/v1/auth/authorize`
- 카카오 로그인 이후 가입 및 로그인 처리 : `Get /api/v1/auth/redirect-kakaologin`

</br>

## 📝 작업 사항
- kakao developer 페이지에서 P난처 Application 생성 및 설정
- 공식문서에서 설명하는 인증로직을 이해한 후 Kakao REST API 분석 진행
- Kakao API를 사용하기 위해 `RestTemplate`을 이용해서 `Json`형식으로 응답받기
    - [인가 코드 받기](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-code), [토큰 받기](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#request-token), [사용자 정보 가져오기](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#req-user-info) API 이용
- kakao developer 페이지에서 P난처 Application 생성 및 설정
- 직렬화 시 순환 참조 문제를 방지하기 위해 `@JsonManagedReference`와 `@JsonIgnore` 어노테이션을 활용해 엔티티 반환 처리 진행

</br>

## 💻 실행 화면

![카카오 로그인](https://github.com/user-attachments/assets/18f86d97-37c8-4133-8fae-5f155b5677c3)

</br>

2024-07-31 06:32 UTC, Dada-none requested changes
getKakaoAccessTokem -> getKakaoAccessToken 수정 필요해보입니다.

2024-07-31 06:36 UTC, Dada-none commented on src/main/java/com/haribo/auth_service/auth/application/service/AuthServiceImpl.java
> +        String accessToken = getKakaoAccessTokem(code);
getKakaoAccessTokem -> getKakaoAccessToken 수정 필요해보입니다👍👼👍

2024-07-31 08:03 UTC, Dada-none requested changes
간결하게 정리되어 흐름을 읽는데 어려움이 없었습니다!

2024-07-31 08:40 UTC, dwd9999 requested changes
고생하셨습니다~

2024-07-31 08:40 UTC, dwd9999 commented on src/main/java/com/haribo/auth_service/member/domain/ProfileMember.java
> +}
Builder 패턴 사용하실거면 Setter 빼셔도 될거같습니다~

2024-07-31 08:40 UTC, dwd9999 commented on src/main/java/com/haribo/auth_service/auth/domain/AuthMember.java
> +}
Builder 패턴 사용하실거면 Setter 빼셔도 될거같습니다~

2024-08-01 00:25 UTC, fsm12 commented on src/main/java/com/haribo/auth_service/auth/application/service/AuthServiceImpl.java
> +        String accessToken = getKakaoAccessTokem(code);
꺄아... 그렇네요..? 얼른 수정하겠습니다!!

2024-08-01 00:26 UTC, fsm12 commented on src/main/java/com/haribo/auth_service/member/domain/ProfileMember.java
> +}
오호 넵~

2024-08-01 01:48 UTC, cocorini commented on src/main/java/com/haribo/auth_service/common/entity/BaseTimeEntity.java
EntityListener 사용하신 거 좋은 거같아요! 또 하나 배웠습니다!

2024-08-01 01:48 UTC, cocorini commented
고생하셨습니다!

2024-08-01 01:54 UTC, cocorini approved these changes
고생하셨습니다!!

2024-08-01 01:55 UTC, dwd9999 approved these changes
고생하셨습니다~

2024-08-01 01:56 UTC, Dada-none approved these changes
고생하셨습니다~

2024-08-01 02:27 UTC, merged